### Mendapatkan semua data produk (GET)
GET http://localhost:5000/products

### Mendapatkan data produk berdasarkan ID (GET)
GET http://localhost:5000/products/1

### Menambahkan produk baru (POST)
POST http://localhost:5000/products
Content-Type: application/json

{
  "productnam": "Keyboard",
  "category": "Device Computer",
  "price": 90000,
  "stock": 15
}

### Memperbarui data produk (PATCH)
PATCH http://localhost:5000/products/1
Content-Type: application/json

{
  "productname": "Speaker Active 1500 Watt",
  "category": "Device Computer",
  "price": 750000,
  "stock": 3
}

### Menghapus data produk (DELETE)
DELETE http://localhost:5000/products/1

//=====================================//

### Mendapatkan semua data karyawan (GET)
GET http://localhost:5000/karyawan

### Mendapatkan data karyawan berdasarkan ID (GET)
GET http://localhost:5000/karyawan/1

### Menambahkan data karyawan baru (POST)
POST http://localhost:5000/karyawan
Content-Type: application/json

{
  "namakary": "Budi Santoso",
  "jeniskelamin": "Laki-laki",
  "jabatan": "Software Engineer",
  "pendidikan": "S1 Informatika"
}

### Memperbarui data karyawan (PATCH)
PATCH http://localhost:5000/karyawan/1
Content-Type: application/json

{
  "namakary": "Budi Santoso Updated",
  "jeniskelamin": "Laki-laki",
  "jabatan": "Senior Developer",
  "pendidikan": "S1 Informatika"
}

### Menghapus data karyawan (DELETE)
DELETE http://localhost:5000/karyawan/1